### PR TITLE
G.h DATA logo update

### PR DESCRIPTION
**Pull request by rkassa**
new logo for "list" as "G.h | Data"

### CODE REVIEW

**Review by allysonjp715 — APPROVED** [review]

**Comment by joe-brilliant** [comment]
Thanks all, the Google team has requested we make this change ASAP this week so they can capture the Data page correctly in the product shots for the video they are producing. Can we push this live this week? Maybe tomorrow?

**Comment by joe-brilliant** [comment]
Hi all just wanted to quickly flag that we'll need to change List to Data in the header and body text on the login page too  https://curator.ghdsi.org/ (also should swap out IHME logo for U of W to stay consistent) Thanks! 

https://www.dropbox.com/s/0od4f1j3h2c9y5t/Screen%20Shot%202020-12-14%20at%209.11.16%20AM.png?dl=0

**Comment by Mougk** [comment]
yep, agree with that change. make consistent across the board.

**Comment by calremmel** [comment]
Noticing some failing tests. Are we good to ignore those for now, or do they need attention? @rkassa Just let me know!

**Comment by rkassa** [comment]
> Noticing some failing tests. Are we good to ignore those for now, or do they need attention? @rkassa Just let me know!

@calremmel ...the only change in the pr is a replacement of the logo's svg file. so if any tests are failing, they probably already were.

**Pull request merged**
