### PR TITLE
1483 variant field

### PR DESCRIPTION
**Pull request by iamleeg**
Hi folks,

I'd appreciate some help with the Cypress test here. I'm getting the failure below, because the input element used in the test is hidden. What I'm trying to do is to click on the TOC entry for Variants of Concern, _then_ interact with the input. Looking at the screenshot on failure, the TOC navigation isn't happening. Anyone got an idea how to work around this?

New case form -- Can add row to linelist with variant of concern (failed)

```
  1) New case form
       Can add row to linelist with variant of concern:
     CypressError: Timed out retrying: `cy.type()` failed because this element is not visible:

`<input name="variantName" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput" value="">`

This element `<input.MuiSelect-nativeInput>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:

`<div class="MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input" tabindex="0" role="button" aria-haspopup="listbox" aria-labelledby="mui-component-select-variantName" id="mui-component-select-variantName">...</div>`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at $Cy.ensureVisibility (http://localhost:3002/__cypress/runner/cypress_runner.js:161186:24)
      at runAllChecks (http://localhost:3002/__cypress/runner/cypress_runner.js:150111:14)
      at retryActionability (http://localhost:3002/__cypress/runner/cypress_runner.js:150154:16)
      at tryCatcher (http://localhost:3002/__cypress/runner/cypress_runner.js:10325:23)
      at Function.Promise.attempt.Promise.try (http://localhost:3002/__cypress/runner/cypress_runner.js:7599:29)
      at tryFn (http://localhost:3002/__cypress/runner/cypress_runner.js:165474:24)
      at whenStable (http://localhost:3002/__cypress/runner/cypress_runner.js:165515:12)
      at http://localhost:3002/__cypress/runner/cypress_runner.js:165033:16
      at tryCatcher (http://localhost:3002/__cypress/runner/cypress_runner.js:10325:23)
      at Promise._settlePromiseFromHandler (http://localhost:3002/__cypress/runner/cypress_runner.js:8260:31)
      at Promise._settlePromise (http://localhost:3002/__cypress/runner/cypress_runner.js:8317:18)
      at Promise._settlePromise0 (http://localhost:3002/__cypress/runner/cypress_runner.js:8362:10)
      at Promise._settlePromises (http://localhost:3002/__cypress/runner/cypress_runner.js:8442:18)
      at Promise._fulfill (http://localhost:3002/__cypress/runner/cypress_runner.js:8386:18)
      at http://localhost:3002/__cypress/runner/cypress_runner.js:10000:46
  From Your Spec Code:
      at Context.eval (http://localhost:3002/__cypress/tests?p=cypress/integration/components/NewCaseForm.spec.ts:154:45)
```

### CODE REVIEW

**Comment by iamleeg** [comment]
Also not sure why the build script fails in CI, there is no clear difference in environment.

**Comment by maciekz1996** [comment]
@iamleeg I don't have much experience with Cypress, but have you tried adding some delay before attempting using `cy.type()` after clicking VARIANT OF CONCERN ?

**Comment by iamleeg** [comment]
Thanks @maciekz1996, I'll try that :)

**Comment by iamleeg** [comment]
Waiting for 500ms didn't work, sadly, and the scroll animation should take much less time than that. I don't want to hold this up any longer, the unit tests work and the data definitely gets written to mongodb so I'm opening this up as ready.

**Review by calremmel — APPROVED** [review]
Looks great to me!

**Pull request merged**
