### PR TITLE
Add a catch all redirect to /

### LINKED ISSUE #1205: Redirect to home page or add custom 404 page?
Currently only https://curator.ghdsi.org/ shows the welcome screen when logged out. https://curator.ghdsi.org/cases or anything else shows a blank screen. We should show the welcome screen on any https://curator.ghdsi.org/ URL when logged out.

### PR DESCRIPTION
**Pull request by allysonjp715**
#1205

### CODE REVIEW

**Review by attwad — COMMENTED** [review]
Looks okay but shouldn't we redirect to a custom 404 instead when something isn't found?

**Comment by allysonjp715** [comment]
> Looks okay but shouldn't we redirect to a custom 404 instead when something isn't found?

Potentially a product decision? This is easier in the name of time and no UX for a 404 page.

**Review by attwad — APPROVED** [review]
okay let's submit this but let's also flag the issue with the product and UX tag and not fix it with this PR.

**Comment by allysonjp715** [comment]
> okay let's submit this but let's also flag the issue with the product and UX tag and not fix it with this PR.

Sounds good will do

**Pull request merged**
