### PR TITLE
2223 iso country codes

### PR DESCRIPTION
**Pull request by iamleeg**
For #2223, use ISO-3166-1 alpha-2 country codes everywhere.

~Draft for two reasons, putting review up to~ Please can we discuss reason 2 and get feedback on the parts that are done:

1. ~Still need to change ingestion to send country codes instead of country names.~
2. The migration for this change is one of those big, "read every case and change its content" migrations that we know went really badly the last time we tried. I don't yet know what to do about that.

The _workaround_ last time was that I wrote a script that ran in mongosh and used its batch update facility. That vastly sped up the migration. I think it's possible to do that within the migration script, though I couldn't work out how due to the interactions between the batches and the `async` functions here, so if anyone is able to fix that up I'd welcome it. Otherwise we can go down the same route of a script that is applied using mongosh: we need to work out where to commit that, how to document its purpose (someone has to run it manually in dev and prod)…we never did that for the confirmation date migration so there's currently a gap between the recorded migration path in the repo and reality.

Or maybe there's some other approach someone can recommend that will work well!

### CODE REVIEW

**Review by jim-sheldon — APPROVED** [review]

**Comment by iamleeg** [comment]
The failure in ingestion CI is an unrelated bug: #2369.

**Comment by abhidg** [comment]
Looks good! Do the country names from iso3166 match what we have in the db? I am thinking of a hypothetical scenario where we migrate up from United States -> US and migration down gives US -> United States of America.

**Comment by iamleeg** [comment]
They may not—they're the official country names. In general as I note in the comment we can't guarantee that the migration is genuinely reversible; in addition to well-known aliases (e.g. United States for the United States of America) there may be multiple values (e.g. USA, US, America) or even bad data (e.g. Algiers). I've made a hopefully-acceptable compromise that the result of the "down" migration is that countries are stored by name.

In fact due to the performance issues with running the migration noted above, I think that I won't change the data in the migration at all, but will have a separate script that gets run manually in mongoose, as I ended up with for confirmation dates. That means there's no need to specify what "down" looks like at all at the moment, other than changing the validation rules.

**Review by abhidg — APPROVED** [review]

**Comment by iamleeg** [comment]
Of course I don't know how to write the separate helper script either :(. In mongosh we don't have access to the project's `npm_modules` so I can't use `i18n-iso-countries` from the helper. Gah.

**Comment by iamleeg** [comment]
oh! Apparently [I can use node_modules](https://docs.mongodb.com/mongodb-shell/write-scripts/require-external-modules/) \o/

**Comment by iamleeg** [comment]
Re-requesting review due to changes to migration approach.

**Review by jim-sheldon — APPROVED** [review]

**Pull request merged**
