### PR TITLE
1607 scale pagination

### PR DESCRIPTION
**Pull request by maciekz1996**
#1607 

⚠️ Before pushing to production this solution should be tested on larger data source to see if the performance is good enough

**Changes**
* Added `count_limit` param to `GET /api/cases` query 
* Document count is being limited do `count_limit` param making the queries faster and Linelist pagination displays 'of many' as total results count
* Updated `openapi.yaml`

### CODE REVIEW

**Review by sergioloporto — APPROVED** [review]

**Comment by iamleeg** [comment]
Tried with 1.1M cases in a local db, does seem perceptibly faster :+1:

**Comment by iamleeg** [comment]
Unfortunately I think you'll need to rework the back-end changes before this can merge :(. I switched from `collection.find()` to `collection.aggregate()` in #1620 to support excluding the GISAID data, so there isn't a count query any more it's a phase in the aggregation pipeline.

**Review by iamleeg — CHANGES_REQUESTED** [review]
Needs to integrate with the aggregation pipeline, sorry :(

**Comment by maciekz1996** [comment]
@iamleeg Ok, I will work on that 👍

**Review by iamleeg — APPROVED** [review]
Thank you!

**Pull request merged**
