### PR TITLE
add UUIDs to Mexico parser

### PR DESCRIPTION
**Pull request by calremmel**
This PR adds `ID_REGISTRO` as the UUID for the Mexico parser.

### CODE REVIEW

**Review by AnyaLindstromBattle — APPROVED** [review]
This looks great to me

**Comment by AnyaLindstromBattle** [comment]
Approved with the caveat that I can't actually look at the data or the data dictionary (only people in the US can access the data for some reason!) to check if ID_REGISTRO is indeed a UUID. Could you perhaps upload the data dict here?

**Comment by calremmel** [comment]
> Approved with the caveat that I can't actually look at the data or the data dictionary (only people in the US can access the data for some reason!) to check if ID_REGISTRO is indeed a UUID. Could you perhaps upload the data dict here?

Sure! The relevant line in the dict is: ID_REGISTRO: Número identificador del caso

[201128 Descriptores_.xlsx](https://github.com/globaldothealth/list/files/5804160/201128.Descriptores_.xlsx)

**Comment by AnyaLindstromBattle** [comment]
Great, all looks spot on!

**Pull request merged**
