### PR TITLE
1508 - Update partner logos

### PR DESCRIPTION
**Pull request by maciekz1996**
- [x] Update all partner logos on sign up interstitial

**Changes**

* Added new logos to `assets/partner-logos`
* Created `PartnerLogos.tsx` component
* Replaced hardcoded colors in LandingPage component
* Changed sign up interstitial width to 1000px
* Updated LandingPage tests

**Screenshots**

Big screen:
Screen Shot 2021-02-09 at 11 53 46

Smaller screen:
Screen Shot 2021-02-09 at 11 53 57

### CODE REVIEW

**Review by sergioloporto — APPROVED** [review]

**Comment by joe-brilliant** [comment]
Hi @sergioloporto @maciekz1996 @WeronikaMichaluk @calremmel, based on user feedback and best practices, would it be possible to make the newsletter sign up a separate and non-required tickbox on registration that we can track separately? Also we now have the UW logo to replace the IHME logo which should now go at the end (right side) to keep them in alphabetical order. Thanks all!

**Comment by joe-brilliant** [comment]
@Mougk any preference on including funders here? It's our call

**Comment by Mougk** [comment]
Let's keep funders in here.

Agree with separate tickbox for newsletter.

**Comment by maciekz1996** [comment]
@joe-brilliant @Mougk Sure, this is possible. I've created new issue for that: https://github.com/globaldothealth/list/issues/1546 and will start working on it !

**Pull request merged**
