### PR TITLE
fixed /cases/

### PR DESCRIPTION
**Pull request by sergioloporto**
Now `/cases/` redirects to `/cases`

### CODE REVIEW

**Review by maciekz1996 — COMMENTED** [review]
I wonder if using `.htaccess` file for stripping out trailing slashes from urls wouldn't be a better solution to this issue 🤔

**Review by maciekz1996 — DISMISSED** [review]

**Review by maciekz1996 — APPROVED** [review]
Looks good 👍

**Comment by abhidg** [comment]
@maciekz1996 @sergioloporto Is the diff to package-lock.json required for this? If not, I'll cherry pick the one-line diff to merge.

**Comment by sergioloporto** [comment]
@abhidg  I just removed that file.
It should be now good to go

**Comment by abhidg** [comment]
Somehow this was already merged, perhaps from another PR, so closing this.

**Comment by abhidg** [comment]
nvm, it wasn't actually merged

**Pull request merged**
