### PR TITLE
Run tests locally

### PR DESCRIPTION
**Pull request by jim-sheldon**
Bumped mongodb-client-encryption version in curator service UI (fixing an error on `npm install`)
Added dependency checks installs to test script
Added stack run check and startup to test script
Updated README

### CODE REVIEW

**Comment by abhidg** [comment]
@maciekz1996 Adding you to reviewers as this updates frontend code

**Comment by jim-sheldon** [comment]
Cypress and data service tests fail

**Comment by abhidg** [comment]
I get this error when trying to './run_stack.sh`

```
curator_1    | [nodemon] starting `tsc -p tsconfig.build.json && node ./dist/server.js`
dev_data_1 exited with code 0
curator_1    | error TS18003: No inputs were found in config file '/usr/src/app/verification/curator-service/api/tsconfig.build.json'. Specified 'include' paths were '["src/**/*","**/*.test.ts"]' and 'exclude' paths were '["node_modules","dist","test","**/*test.ts"]'.
```

I don't know enough Node, so probably just a misconfiguration on my end.

**Comment by jim-sheldon** [comment]
> I get this error when trying to './run_stack.sh`
> 
> ```
> curator_1    | [nodemon] starting `tsc -p tsconfig.build.json && node ./dist/server.js`
> dev_data_1 exited with code 0
> curator_1    | error TS18003: No inputs were found in config file '/usr/src/app/verification/curator-service/api/tsconfig.build.json'. Specified 'include' paths were '["src/**/*","**/*.test.ts"]' and 'exclude' paths were '["node_modules","dist","test","**/*test.ts"]'.
> ```
> 
> I don't know enough Node, so probably just a misconfiguration on my end.

Hmm...unsure, as I do not know Node well, nor can I reproduce that error.
The `run_stack` script does wrap docker-compose, so all other things equal we should see the same behavior as we share that environment.

Curious that `dev_data_1` exits 0, mine stays up, with output: 

```
data_1       | [nodemon] 2.0.4
data_1       | [nodemon] to restart at any time, enter `rs`
data_1       | [nodemon] watching path(s): src/**/* api/**/*
data_1       | [nodemon] watching extensions: ts,yaml
data_1       | [nodemon] starting `tsc -p tsconfig.build.json && node ./dist/server.js`
curator_1    | [nodemon] 2.0.4
curator_1    | [nodemon] to restart at any time, enter `rs`
curator_1    | [nodemon] watching path(s): src/**/* openapi/**/*
curator_1    | [nodemon] watching extensions: ts,yaml
curator_1    | [nodemon] starting `tsc -p tsconfig.build.json && node ./dist/server.js`
``` 

Perhaps not enough system resources for Docker to keep all the containers running at once?

If you like, we can pair on this tomorrow. If we can't figure it out quickly, I can open a separate issue for it.

**Review by iamleeg — APPROVED** [review]
Nice!

**Pull request merged**
