### PR TITLE
Omicron dropdown

### PR DESCRIPTION
**Pull request by iamleeg**
When we inevitably decide that we want to track the omicron variant, merge this.

### CODE REVIEW

**Review by jim-sheldon — APPROVED** [review]

**Comment by iamleeg** [comment]
Will wait for the tests to re-run: saw a failure on this branch earlier with no code changes and I'd like to see why. If it's the thing with Italy going missing I'll just merge it.

**Comment by joe-brilliant** [comment]
Thanks for jumping on this so quickly all, let's go ahead and to production as soon as possible. Relatedly, we may want consider adding in all official WHO VoCs so we're fully up to date: https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/

Would it be possible / make sense to add the greek names in parentheses or vice versa with the pango lineage?

**Comment by iamleeg** [comment]
I actually did add the other VoCs, did you want the VoIs too? Can add the name, but I'd prefer to do it as a separate field so we can track unnamed variants if desired.

**Comment by joe-brilliant** [comment]
I think just all VOCs are fine for now. Agreed "Pango Lineage" and "WHO Label" should be separate collumns but we can add that later. cc: @Mougk for his input. Would be great to get this change in to prod first thanks all!

**Pull request merged**
