### PR TITLE
Add undocumented fields to the case schema

### PR DESCRIPTION
**Pull request by iamleeg**
Proposed fix for #1622, not sure if complete though so @fojackson8 / @AnyaLindstromBattle any other information missing?

### CODE REVIEW

**Review by calremmel — COMMENTED** [review]
Certainly looks good to me! I think that this is the only new field aside from `limitToCountry` which is in there under POST /cases. Anya/Felix please feel free to correct.

**Comment by iamleeg** [comment]
`limitToCountry` is actually documented but I can add examples, and there are parts of the location (geometry, country, geo resolution) that need additions. If you don't see `limitToCountry` documented in the swagger UI, perhaps it isn't getting updated on deployment?

**Comment by iamleeg** [comment]
Ah, got it: the location fields are documented for PUT but not for POST.

**Comment by fojackson8** [comment]
A lot of the VoC data has number of cases > 1. Is number of cases a documented field here?

**Comment by iamleeg** [comment]
@fojackson8 number of cases is already documented for POST (i.e. create new cases), where it works, but not for PUT (i.e. upsert potentially new or existing cases) where it isn't available.

**Review by fojackson8 — APPROVED** [review]
I think that's everything, thanks for adding!

**Pull request merged**
